export {
  BODY_TYPES,
  type BodyType,
  type MoonConfig,
  type PlanetConfig,
  type CelestialBody,
  type MoonBody,
  type PhysicsInput,
  type CollisionEvent,
  type DevourEvent,
  type PhysicsResult,
  DEFAULT_MOUSE_RADIUS,
  BOUNCE_DAMPING,
  MOUSE_FORCE_COEFFICIENT,
  COULOMB_CONSTANT,
  INTERACTION_MIN_DIST,
  INTERACTION_MAX_DIST,
  BLACKHOLE_MAX_RADIUS_RATIO,
  BLACKHOLE_RESET_DELAY_MS,
  COLLISION_SOUND_CHANCE,
  LIGHTNING_DRAW_DIST,
  BLACKHOLE_PULL_DIST,
  BLACKHOLE_PULL_CAP,
  BLACKHOLE_GRAVITY_REF_MASS,
  BLACKHOLE_GRAVITY_MASS_CAP,
  SMALL_ITEM_COUNT,
} from './types';
export {
  SUN_RADIUS,
  SUN_MASS_FACTOR,
  SUN_INITIAL_SPEED,
  SUN_VROT,
  SUN_POSITION_X_FRACTION,
  SUN_POSITION_Y_FRACTION,
  PLANET_ORBIT_START_RADIUS,
  PLANET_ORBIT_STEP,
  PLANET_SPEED_BASE,
  PLANET_SPEED_RANDOM,
  SUN_GRAVITY_CONSTANT,
  BLACKHOLE_RADIUS,
  BLACKHOLE_MASS,
  BLACKHOLE_VROT,
  BLACKHOLE_POSITION_X_FRACTION,
  BLACKHOLE_POSITION_Y_FRACTION,
  BLACKHOLE_INITIAL_VX,
  BLACKHOLE_INITIAL_VY,
  SMALL_ITEM_RADIUS_MIN,
  SMALL_ITEM_RADIUS_RANGE,
  SMALL_ITEM_SPEED,
  SMALL_ITEM_MASS_FACTOR,
  SMALL_ITEM_VROT_RANGE,
  MATH_SYMBOLS,
  PLANET_CONFIGS,
} from './config';
export {
  resetIdCounter,
  createSun,
  createPlanet,
  createBlackhole,
  createSmallItem,
} from './create-body';
export {
  stepPosition,
  applyBoundary,
  applyMouseForce,
  interactPair,
  type InteractPairResult,
  applySunGravity,
  applyBlackholePull,
  applyBlackholeDevour,
  type DevourResult,
  computeForceMult,
  updatePhysics,
} from './physics';
