import type { LessonContent } from '../src/types';

export const sampleLessons: LessonContent[] = [
  {
    id: 'lesson-physics-forces',
    version: '1.0.0',
    metadata: {
      conceptId: 'newtons-second-law',
      displayName: "Newton's Second Law",
      subject: 'physics',
      gradeLevels: [9, 10, 11, 12],
      prerequisites: ['force', 'mass', 'acceleration'],
      estimatedTimeMinutes: 15,
      commonMisconceptions: ['force-is-property-of-object'],
      tags: ['physics', 'mechanics', 'forces'],
    },
    sections: [
      {
        id: 's1',
        kind: 'story',
        body: 'Every time you push a shopping cart, punch a ball, or stomp on a brake pedal — you\'re having a quiet conversation with Newton. Most people think force is some kind of "stuff" living inside objects. It\'s not. Force is what happens *between* things — a relationship, not a possession.',
        heading: 'The Hidden Conversation',
      },
      {
        id: 's2',
        kind: 'analogy',
        body: 'Think of it like this: imagine two ice skaters facing each other. When one pushes, *both* move. The pusher doesn\'t "own" the force — they just started the exchange. Force is the shove, the pull, the tension. It only exists while the interaction is happening.',
        heading: 'The Skater Analogy',
      },
      {
        id: 's3',
        kind: 'equation',
        body: 'F = m·a',
        symbol: 'F',
        heading: 'The Rule',
      },
      {
        id: 's4',
        kind: 'narrative',
        body: 'What this really says is: how fast something speeds up depends on two things — how heavy it is, and how hard you push. Push harder, it accelerates more. Double the mass? It needs double the force for the same acceleration. That\'s why a truck takes longer to stop than a bicycle — not because it\'s "stubborn," but because it has more inertia.',
        heading: 'What\'s Really Going On',
      },
      {
        id: 's5',
        kind: 'misconception',
        body: 'A lot of students think force is a property of the object — like "the ball has force in it." Nope. Force is what\'s done *to* an object. Once you stop pushing, the force is gone. The ball keeps moving because of inertia, not because it\'s "carrying" force.',
        heading: 'Common Trap',
      },
      {
        id: 's6',
        kind: 'try-this',
        body: 'Grab a heavy book and a light pen. Push both across a table with the same effort. Which one accelerates faster? Now push the book harder — what happens? You just demonstrated F = m·a with your own hands.',
        heading: 'Try This',
      },
    ],
    questions: [
      {
        id: 'q1',
        prompt: 'A cyclist and a bus are both pedaling/accelerating from rest. Which one needs more force to reach the same speed in the same time?',
        options: ['The cyclist', 'The bus', 'They need the same force', 'It depends on the color'],
        correctIndex: 1,
        explanation: 'The bus has more mass, so to get the same acceleration (reaching the same speed in the same time), it needs proportionally more force. F = m·a — bigger m, bigger F.',
        conceptId: 'newtons-second-law',
        difficulty: 'easy',
      },
      {
        id: 'q2',
        prompt: 'A 5 kg box is pushed with 20 N of force. What\'s its acceleration?',
        options: ['2 m/s²', '4 m/s²', '5 m/s²', '100 m/s²'],
        correctIndex: 1,
        explanation: 'a = F/m = 20/5 = 4 m/s². The units work out: N/kg = (kg·m/s²)/kg = m/s².',
        conceptId: 'newtons-second-law',
        difficulty: 'medium',
      },
    ],
    simulations: [],
  },
  {
    id: 'lesson-chemistry-acids',
    version: '1.0.0',
    metadata: {
      conceptId: 'ph-scale',
      displayName: 'The pH Scale',
      subject: 'chemistry',
      gradeLevels: [9, 10, 11],
      prerequisites: ['acids', 'bases'],
      estimatedTimeMinutes: 12,
      commonMisconceptions: ['ph-0-is-strongest'],
      tags: ['chemistry', 'acids-bases'],
    },
    sections: [
      {
        id: 's7',
        kind: 'story',
        body: 'Your stomach is basically a bag of hydrochloric acid with a pH around 1.5. Every time you eat, that acid attacks your food — and somehow your stomach lining survives. The pH scale isn\'t just a number — it\'s a measure of how aggressively hydrogen ions are prowling around, looking to react.',
        heading: 'Your Built-In Acid Tank',
      },
      {
        id: 's8',
        kind: 'narrative',
        body: 'pH is a logarithmic scale — which means each step is a *tenfold* change. A pH of 3 isn\'t slightly more acidic than pH 4 — it\'s TEN times more acidic. A pH of 2? A hundred times more acidic than pH 4. That\'s why a tiny pH difference can be the difference between "fine" and "corrosive as hell."',
        heading: 'The Logarithmic Trap',
      },
      {
        id: 's9',
        kind: 'equation',
        body: 'pH = −log₁₀[H⁺]',
        heading: 'The Math',
      },
      {
        id: 's10',
        kind: 'misconception',
        body: 'Many students think pH 0 means "no acid." Actually, pH 0 means the *strongest* acidic concentration. The scale runs 0 (strongly acidic) through 7 (neutral) to 14 (strongly basic). Lower number = more acidic. Higher number = more basic. Don\'t let the direction fool you.',
        heading: 'The Backwards Feeling',
      },
      {
        id: 's11',
        kind: 'fun-fact',
        body: 'Lemon juice (pH ~2) is about 100,000 times more acidic than coffee (pH ~5). That\'s five orders of magnitude — the same difference as comparing a meter to a hundred kilometers.',
        heading: 'Scale Shock',
      },
    ],
    questions: [
      {
        id: 'q3',
        prompt: 'If Solution A has pH 2 and Solution B has pH 5, how many times more acidic is Solution A?',
        options: ['3 times', '30 times', '100 times', '1000 times'],
        correctIndex: 3,
        explanation: 'Each pH step is a 10× difference. From pH 2 to pH 5 is 3 steps: 10 × 10 × 10 = 1,000 times more acidic.',
        conceptId: 'ph-scale',
        difficulty: 'easy',
      },
    ],
    simulations: [],
  },
  {
    id: 'lesson-math-pythagoras',
    version: '1.0.0',
    metadata: {
      conceptId: 'pythagorean-theorem',
      displayName: 'Pythagorean Theorem',
      subject: 'mathematics',
      gradeLevels: [8, 9, 10],
      prerequisites: ['squares', 'square-roots'],
      estimatedTimeMinutes: 10,
      commonMisconceptions: ['hypotenuse-is-longest-leg'],
      tags: ['mathematics', 'geometry'],
    },
    sections: [
      {
        id: 's12',
        kind: 'story',
        body: 'Pythagoras didn\'t "discover" this theorem — Babylonians used it over a thousand years before him. What he (or his cult) did was prove it. There are over 370 known proofs of this one little equation. Three hundred seventy different ways to show that a² + b² = c² is unassailable.',
        heading: 'The Theorem That Won\'t Die',
      },
      {
        id: 's13',
        kind: 'narrative',
        body: 'Imagine a right-angled triangle. Square each side. Now look at the areas: the two smaller squares, added together, always equal the biggest square. That\'s it. That\'s the whole theorem. It\'s not about "solving for x" — it\'s about a deep, unavoidable relationship baked into flat geometry.',
        heading: 'What It Actually Says',
      },
      {
        id: 's14',
        kind: 'equation',
        body: 'a² + b² = c²',
        symbol: 'c',
        heading: 'The Relationship',
      },
      {
        id: 's15',
        kind: 'try-this',
        body: 'Draw a right triangle with legs 3 cm and 4 cm. Measure the hypotenuse — it should be exactly 5 cm. Now calculate: 3² + 4² = 9 + 16 = 25. √25 = 5. Magic? No — math.',
        heading: 'Prove It to Yourself',
      },
    ],
    questions: [],
    simulations: [],
  },
];
