#!/usr/bin/env node
// Generates docs/REPOSITORY_HEALTH.md from package ARCHITECTURE.toml files,
// package.json versions, and vitest coverage floors. Run via `pnpm docs:sync`.
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';

const root = join(process.cwd());
const target = join(root, 'docs', 'REPOSITORY_HEALTH.md');

function parseToml(src) {
  const obj = {};
  for (const rawLine of src.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      const inner = val.slice(1, -1).trim();
      obj[key] = inner === '' ? [] : inner.split(',').map((s) => s.trim().replace(/^["']|["']$/g, ''));
    } else if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      obj[key] = val.slice(1, -1);
    } else {
      obj[key] = val;
    }
  }
  return obj;
}

function readJson(p) {
  return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null;
}

function coverageFloor(dir) {
  const vc = join(dir, 'vitest.config.ts');
  if (!existsSync(vc)) return '—';
  const src = readFileSync(vc, 'utf8');
  const m = src.match(/lines:\s*(\d+)/);
  return m ? `${m[1]}%` : '—';
}

function bundleSize(dir) {
  const dist = join(dir, 'dist');
  if (!existsSync(dist)) return '—';
  let total = 0;
  for (const f of readdirSync(dist)) {
    if (f.endsWith('.js')) total += statSync(join(dist, f)).size;
  }
  return total === 0 ? '—' : `${(total / 1024).toFixed(1)} kB`;
}

const packages = [];
for (const scopeName of ['packages', 'apps']) {
  const scope = join(root, scopeName);
  if (!existsSync(scope)) continue;
  for (const name of readdirSync(scope)) {
    const dir = join(scope, name);
    if (!statSync(dir).isDirectory()) continue;
    const tomlPath = join(dir, 'ARCHITECTURE.toml');
    const pkg = readJson(join(dir, 'package.json'));
    packages.push({
      name: `${scopeName}/${name}`,
      version: pkg?.version ?? '—',
      meta: existsSync(tomlPath) ? parseToml(readFileSync(tomlPath, 'utf8')) : {},
      coverage: coverageFloor(dir),
      size: bundleSize(dir),
    });
  }
}

packages.sort((a, b) => a.name.localeCompare(b.name));

const rows = packages
  .map((p) => {
    const status = p.meta.status || 'unknown';
    const maturity = p.meta.maturity || '—';
    const contracts = Array.isArray(p.meta.contracts) && p.meta.contracts.length ? p.meta.contracts.join(', ') : '—';
    const deps = Array.isArray(p.meta.dependencies) && p.meta.dependencies.length ? p.meta.dependencies.join(', ') : '—';
    return `| ${p.name} | ${p.version} | ${status} | ${maturity} | ${p.coverage} | ${p.size} | ${contracts} | ${deps} |`;
  })
  .join('\n');

const byStatus = {};
for (const p of packages) {
  const s = p.meta.status || 'unknown';
  byStatus[s] = (byStatus[s] || 0) + 1;
}
const summary = Object.entries(byStatus)
  .map(([k, v]) => `${k}: ${v}`)
  .join(' · ');

const generated = `Generated by \`pnpm docs:sync\` (scripts/generate-health.mjs). Do not hand-edit.

<!-- AUTO:health:start -->
| Package | Version | Status | Maturity | Coverage floor | Dist size | Contracts | Dependencies |
|---------|---------|--------|----------|----------------|-----------|-----------|--------------|
${rows}

**Summary:** ${summary}
<!-- AUTO:health:end -->`;

const markerStart = '<!-- AUTO:health:start -->';
const markerEnd = '<!-- AUTO:health:end -->';

let out;
if (!existsSync(target)) {
  out = `# Health Dashboard\n\n${generated}`;
} else {
  const existing = readFileSync(target, 'utf8');
  if (existing.includes(markerStart) && existing.includes(markerEnd)) {
    out = existing.replace(/<!-- AUTO:health:start -->[\s\S]*?<!-- AUTO:health:end -->/, generated);
  } else {
    out = existing + `\n${generated}\n`;
  }
}
writeFileSync(target, out);
console.log(`[generate-health] ✓ ${target}`);
