import type { QuizQuestion, SubjectKey } from './types';

const RAW_QUESTIONS: Record<SubjectKey, Array<{
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  conceptId: string;
  displayName: string;
  prerequisites: string[];
  gradeLevels: number[];
  estimatedTimeMinutes: number;
  commonMisconceptions: string[];
  tags: string[];
}>> = {
  physics: [
    {
      question: "Which of Newton's Laws states that 'For every action, there is an equal and opposite reaction'?",
      options: ['First Law', 'Second Law', 'Third Law', 'Law of Gravitation'],
      correct: 2,
      explanation: "Newton's 3rd Law of Motion dictates that forces always occur in equal and opposite action-reaction pairs!",
      conceptId: 'newtons-third-law',
      displayName: "Newton's Third Law of Motion",
      prerequisites: ['force', 'interaction'],
      gradeLevels: [9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['action-reaction-cancel', 'only-contact-forces'],
      tags: ['physics', 'mechanics', 'forces', 'newton'],
    },
    {
      question: 'What is the Speed of Light in a vacuum?',
      options: ['3 \u00D7 10\u2078 m/s', '3 \u00D7 10\u2076 m/s', '1.5 \u00D7 10\u2078 m/s', '300,000 m/s'],
      correct: 0,
      explanation: "Light travels at approximately 300,000,000 meters per second (3 \u00D7 10\u2078 m/s) in a vacuum, represented by the constant 'c'!",
      conceptId: 'speed-of-light',
      displayName: 'Speed of Light',
      prerequisites: ['waves', 'electromagnetic-spectrum'],
      gradeLevels: [9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['light-instantaneous', 'light-needs-medium'],
      tags: ['physics', 'optics', 'electromagnetism'],
    },
    {
      question: "According to Ohm's Law, what is the relation between Voltage (V), Current (I), and Resistance (R)?",
      options: ['V = I / R', 'V = I \u00D7 R', 'I = V \u00D7 R', 'R = V \u00D7 I'],
      correct: 1,
      explanation: "Ohm's Law states that Voltage equals Current multiplied by Resistance (V = I \u00D7 R).",
      conceptId: 'ohms-law',
      displayName: "Ohm's Law",
      prerequisites: ['current', 'voltage', 'resistance'],
      gradeLevels: [10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['voltage-causes-current-directly', 'resistance-is-constant'],
      tags: ['physics', 'electricity', 'circuits'],
    },
    {
      question: 'Which particle in an atom carries a negative electric charge?',
      options: ['Proton', 'Neutron', 'Electron', 'Photon'],
      correct: 2,
      explanation: 'Electrons carry a negative charge (-1.6 \u00D7 10\u207B\u00B9\u2079 C) and orbit around the atomic nucleus.',
      conceptId: 'atomic-structure',
      displayName: 'Atomic Structure',
      prerequisites: ['atoms', 'elements'],
      gradeLevels: [8, 9, 10],
      estimatedTimeMinutes: 1,
      commonMisconceptions: ['protons-move', 'neutrons-charged'],
      tags: ['physics', 'chemistry', 'atomic-structure'],
    },
  ],
  chemistry: [
    {
      question: "What is the most abundant gas in Earth's atmosphere?",
      options: ['Oxygen (O\u2082)', 'Carbon Dioxide (CO\u2082)', 'Nitrogen (N\u2082)', 'Argon (Ar)'],
      correct: 2,
      explanation: "Nitrogen gas (N\u2082) makes up approximately 78% of Earth's atmosphere by volume!",
      conceptId: 'atmospheric-composition',
      displayName: 'Atmospheric Composition',
      prerequisites: ['atmosphere', 'gases'],
      gradeLevels: [8, 9, 10],
      estimatedTimeMinutes: 1,
      commonMisconceptions: ['most-abundant-oxygen', 'co2-primary-gas'],
      tags: ['chemistry', 'earth-science', 'atmosphere'],
    },
    {
      question: 'What is the pH value of pure distilled water at 25\u00B0C?',
      options: ['0', '7', '14', '5.5'],
      correct: 1,
      explanation: 'Pure water has a neutral pH of 7. Values below 7 are acidic, while values above 7 are basic/alkaline.',
      conceptId: 'ph-scale',
      displayName: 'pH Scale',
      prerequisites: ['acids', 'bases', 'concentration'],
      gradeLevels: [9, 10, 11],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['water-is-acidic', 'ph-0-is-strongest'],
      tags: ['chemistry', 'acids-bases', 'ph'],
    },
    {
      question: 'Who developed the Periodic Table of Elements in 1869?',
      options: ['Antoine Lavoisier', 'Dmitri Mendeleev', 'John Dalton', 'Ernest Rutherford'],
      correct: 1,
      explanation: 'Dmitri Mendeleev organized chemical elements by atomic mass and predicted the properties of elements yet to be discovered.',
      conceptId: 'periodic-table-history',
      displayName: 'History of the Periodic Table',
      prerequisites: ['elements', 'atomic-mass'],
      gradeLevels: [8, 9, 10],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['mendeleev-discovered-elements', 'modern-table-same-order'],
      tags: ['chemistry', 'history', 'periodic-table'],
    },
    {
      question: 'Which chemical bond involves the sharing of electron pairs between atoms?',
      options: ['Ionic Bond', 'Covalent Bond', 'Metallic Bond', 'Hydrogen Bond'],
      correct: 1,
      explanation: 'Covalent bonding occurs when atoms share valence electrons to achieve stable electronic configurations.',
      conceptId: 'chemical-bonding',
      displayName: 'Chemical Bonding',
      prerequisites: ['valence-electrons', 'octet-rule'],
      gradeLevels: [9, 10, 11],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['covalent-donates-electrons', 'ionic-shares-electrons'],
      tags: ['chemistry', 'bonding', 'molecules'],
    },
  ],
  math: [
    {
      question: 'What is the derivative of x\u00B2 with respect to x?',
      options: ['x', '2x', 'x\u00B3 / 3', '2'],
      correct: 1,
      explanation: 'Using the Power Rule (d/dx [x\u207F] = n\u00B7x\u207F\u207B\u00B9), the derivative of x\u00B2 is 2x\u00B9 = 2x.',
      conceptId: 'power-rule-differentiation',
      displayName: 'Power Rule of Differentiation',
      prerequisites: ['limits', 'functions'],
      gradeLevels: [11, 12],
      estimatedTimeMinutes: 3,
      commonMisconceptions: ['derivative-is-slope-only', 'power-rule-adds-one'],
      tags: ['mathematics', 'calculus', 'differentiation'],
    },
    {
      question: 'What is the value of Sin(90\u00B0) in trigonometry?',
      options: ['0', '0.5', '1', '\u221A3/2'],
      correct: 2,
      explanation: 'Sin(90\u00B0) = 1. On the unit circle, 90 degrees corresponds to the top point (0, 1).',
      conceptId: 'trigonometric-values',
      displayName: 'Trigonometric Values',
      prerequisites: ['angles', 'right-triangles', 'unit-circle'],
      gradeLevels: [10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['sin-max-0.5', 'cos-90-equals-1'],
      tags: ['mathematics', 'trigonometry'],
    },
    {
      question: 'If a right-angled triangle has legs of length 3 and 4, what is the hypotenuse length?',
      options: ['5', '6', '7', '25'],
      correct: 0,
      explanation: 'By the Pythagorean Theorem (a\u00B2 + b\u00B2 = c\u00B2): 3\u00B2 + 4\u00B2 = 9 + 16 = 25, so c = \u221A25 = 5.',
      conceptId: 'pythagorean-theorem',
      displayName: 'Pythagorean Theorem',
      prerequisites: ['squares', 'square-roots', 'triangles'],
      gradeLevels: [8, 9, 10],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['hypotenuse-is-longest-leg', 'a-squared-plus-b-squared-equals-c'],
      tags: ['mathematics', 'geometry', 'pythagoras'],
    },
    {
      question: 'What is the value of 0! (zero factorial)?',
      options: ['0', '1', 'Undefined', 'Infinity'],
      correct: 1,
      explanation: 'By mathematical definition, 0! = 1. This ensures consistency in combinatorics and probability formulas!',
      conceptId: 'factorial-definition',
      displayName: 'Factorial Definition',
      prerequisites: ['multiplication', 'combinatorics'],
      gradeLevels: [10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['zero-factorial-zero', 'factorial-only-integers'],
      tags: ['mathematics', 'combinatorics', 'factorials'],
    },
  ],
  computing: [
    {
      question: 'What is the binary representation of the decimal number 10?',
      options: ['1001', '1010', '1100', '1110'],
      correct: 1,
      explanation: 'In binary: 8 + 0 + 2 + 0 = 10, which corresponds to 1010 in base 2.',
      conceptId: 'binary-numbers',
      displayName: 'Binary Number System',
      prerequisites: ['decimal-system', 'place-value'],
      gradeLevels: [8, 9, 10],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['binary-starts-with-1', 'binary-only-ones'],
      tags: ['computing', 'binary', 'number-systems'],
    },
    {
      question: "Who wrote the world's first computer algorithm?",
      options: ['Alan Turing', 'Charles Babbage', 'Ada Lovelace', 'Grace Hopper'],
      correct: 2,
      explanation: "Ada Lovelace wrote the first computer algorithm in 1843 for Babbage's mechanical Analytical Engine!",
      conceptId: 'history-of-computing',
      displayName: 'History of Computing',
      prerequisites: [],
      gradeLevels: [8, 9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['turing-first-programmer', 'babbage-wrote-software'],
      tags: ['computing', 'history', 'pioneers'],
    },
    {
      question: 'Which data structure follows the First-In, First-Out (FIFO) principle?',
      options: ['Stack', 'Queue', 'Tree', 'Graph'],
      correct: 1,
      explanation: 'A Queue operates on FIFO (First In, First Out), similar to a line of people waiting for a ticket.',
      conceptId: 'queue-data-structure',
      displayName: 'Queue Data Structure',
      prerequisites: ['arrays', 'linked-lists'],
      gradeLevels: [10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['queue-is-lifo', 'stack-and-queue-same'],
      tags: ['computing', 'data-structures', 'algorithms'],
    },
    {
      question: "What does 'CPU' stand for in computer science?",
      options: ['Central Power Unit', 'Central Processing Unit', 'Computer Program Utility', 'Core Process Unit'],
      correct: 1,
      explanation: 'CPU stands for Central Processing Unit\u2014the primary electronic circuit that executes instructions!',
      conceptId: 'computer-architecture',
      displayName: 'Computer Architecture Basics',
      prerequisites: [],
      gradeLevels: [6, 7, 8],
      estimatedTimeMinutes: 1,
      commonMisconceptions: ['cpu-is-computer-brain-literal', 'cpu-stores-data'],
      tags: ['computing', 'hardware', 'architecture'],
    },
  ],
  pioneers: [
    {
      question: 'Which female scientist won two Nobel Prizes in two different scientific fields?',
      options: ['Rosalind Franklin', 'Marie Curie', 'Chien-Shiung Wu', 'Ada Lovelace'],
      correct: 1,
      explanation: 'Marie Curie won Nobel Prizes in Physics (1903) and Chemistry (1911)!',
      conceptId: 'marie-curie',
      displayName: 'Marie Curie',
      prerequisites: ['radioactivity'],
      gradeLevels: [8, 9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['curie-won-one-nobel', 'curie-discovered-radium-only'],
      tags: ['pioneers', 'physics', 'chemistry', 'women-in-stem'],
    },
    {
      question: 'Which ancient mathematician introduced the concept of Zero and calculated Pi accurately?',
      options: ['Euclid', 'Pythagoras', 'Aryabhata', 'Archimedes'],
      correct: 2,
      explanation: 'Aryabhata in 499 CE introduced Zero as a place-value digit and calculated Pi to 3.1416!',
      conceptId: 'aryabhata',
      displayName: 'Aryabhata',
      prerequisites: ['number-systems', 'pi'],
      gradeLevels: [8, 9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['zero-invented-by-arabs', 'aryabhata-only-astronomy'],
      tags: ['pioneers', 'mathematics', 'astronomy', 'india'],
    },
    {
      question: 'Who discovered Photo 51 which revealed the double-helix structure of DNA?',
      options: ['James Watson', 'Francis Crick', 'Rosalind Franklin', 'Gregor Mendel'],
      correct: 2,
      explanation: "Rosalind Franklin captured Photo 51 using X-ray crystallography, proving DNA's double-helix structure.",
      conceptId: 'rosalind-franklin',
      displayName: 'Rosalind Franklin',
      prerequisites: ['dna', 'x-ray-crystallography'],
      gradeLevels: [9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['watson-crick-discovered-dna', 'franklin-assistant-only'],
      tags: ['pioneers', 'biology', 'dna', 'women-in-stem'],
    },
    {
      question: "Which mathematician calculated NASA's Apollo 11 moon mission trajectories?",
      options: ['Katherine Johnson', 'Grace Hopper', 'Margaret Hamilton', 'Ada Lovelace'],
      correct: 0,
      explanation: "Katherine Johnson performed the critical orbital trajectory calculations for NASA's Mercury & Apollo moon missions!",
      conceptId: 'katherine-johnson',
      displayName: 'Katherine Johnson',
      prerequisites: ['orbital-mechanics', 'geometry'],
      gradeLevels: [8, 9, 10, 11, 12],
      estimatedTimeMinutes: 2,
      commonMisconceptions: ['computers-did-all-work', 'nasa-only-had-white-male-mathematicians'],
      tags: ['pioneers', 'mathematics', 'nasa', 'space', 'women-in-stem'],
    },
  ],
};

export const QUIZ_QUESTIONS: QuizQuestion[] = Object.entries(RAW_QUESTIONS).flatMap(
  ([subject, questions]) =>
    questions.map((q, idx) => ({
      id: `${subject}-${idx + 1}`,
      subject: subject as SubjectKey,
      question: q.question,
      options: q.options,
      correct: q.correct,
      explanation: q.explanation,
      conceptId: q.conceptId,
      displayName: q.displayName,
      prerequisites: q.prerequisites,
      gradeLevels: q.gradeLevels,
      estimatedTimeMinutes: q.estimatedTimeMinutes,
      commonMisconceptions: q.commonMisconceptions,
      tags: q.tags,
    })),
);

export function getQuestionsBySubject(subject: SubjectKey): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter((q) => q.subject === subject);
}

export function getQuestionById(id: string): QuizQuestion | undefined {
  return QUIZ_QUESTIONS.find((q) => q.id === id);
}
